version: "3.9" # optional since v1.27.0
services:
  node-app:
    build:
      context: .
      args:
        ENV: PROD
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
