version: "3.9" # optional since v1.27.0
services:
  node-app:
    build:
      context: .
      args:
        ENV: DEV
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3000:80"
