version: "3.9" # optional since v1.27.0
services:
  node-app:
    image: zsaee060/node-app
    env_file:
      - ./.env
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=zaid
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongo-db:
