version: "3.9" # optional since v1.27.0
services:
  node-app:
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
        delay: 15s
    build:
      context: .
      args:
        ENV: PROD
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
